sh ./lrp_llava_hf/scripts/train/1_train_ArxivQA.sh
sh ./lrp_llava_hf/scripts/train/2_train_GeoChat.sh
sh ./lrp_llava_hf/scripts/train/3_train_IconQA.sh
sh ./lrp_llava_hf/scripts/train/4_train_ClevrMath_1.sh
sh ./lrp_llava_hf/scripts/train/4_train_ClevrMath_2.sh
sh ./lrp_llava_hf/scripts/train/5_train_CodeQA_1.sh
sh ./lrp_llava_hf/scripts/train/5_train_CodeQA_2.sh
sh ./lrp_llava_hf/scripts/train/6_train_ImageNet_1.sh
sh ./lrp_llava_hf/scripts/train/6_train_ImageNet_2.sh
sh ./lrp_llava_hf/scripts/train/7_train_Flickr30k_1.sh
sh ./lrp_llava_hf/scripts/train/7_train_Flickr30k_2.sh
sh ./lrp_llava_hf/scripts/train/8_train_DocVQA_1.sh
sh ./lrp_llava_hf/scripts/train/8_train_DocVQA_2.sh
sh ./lrp_llava_hf/scripts/train/9_train_TextVQA_1.sh
sh ./lrp_llava_hf/scripts/train/9_train_TextVQA_2.sh
sh ./lrp_llava_hf/scripts/train/10_train_MathQA_1.sh
sh ./lrp_llava_hf/scripts/train/10_train_MathQA_2.sh
sh ./lrp_llava_hf/scripts/train/11_train_ChartQA_1.sh
sh ./lrp_llava_hf/scripts/train/11_train_ChartQA_2.sh
sh ./lrp_llava_hf/scripts/train/12_train_PathVQA_1.sh
sh ./lrp_llava_hf/scripts/train/12_train_PathVQA_2.sh
sh ./lrp_llava_hf/scripts/train/13_train_Grounding_1.sh
sh ./lrp_llava_hf/scripts/train/13_train_Grounding_2.sh
sh ./lrp_llava_hf/scripts/train/14_train_ScienceQA_1.sh
sh ./lrp_llava_hf/scripts/train/14_train_ScienceQA_2.sh
sh ./lrp_llava_hf/scripts/train/15_train_WikiQA_1.sh
