bash ./lrp/scripts/train/1_ScienceQA_1.sh
bash ./lrp/scripts/train/2_TextVQA_1.sh
bash ./lrp/scripts/train/3_ImageNet_1.sh
bash ./lrp/scripts/train/4_GQA_1.sh
bash ./lrp/scripts/train/4_GQA_2.sh
bash ./lrp/scripts/train/5_VizWiz_1.sh
bash ./lrp/scripts/train/5_VizWiz_2.sh
bash ./lrp/scripts/train/6_Grounding_1.sh
bash ./lrp/scripts/train/6_Grounding_2.sh
bash ./lrp/scripts/train/7_VQAv2_1.sh
bash ./lrp/scripts/train/7_VQAv2_2.sh
bash ./lrp/scripts/train/8_OCRVQA_1.sh
